### ISSUE TITLE
need way to put natives jars on classpath

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#60]
Jerkar does a really good job at downloading jars for dependency libraries and build a classpath for them, but I can't figure out how to get it to download natives jars and add them to the classpath.

Natives jars are other jars attached to the module, like a source jar or a javadoc jar. [Here's an example on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.lwjgl%22). I think the Jerkar dependency resolver calls them attached artifacts.

I can find in the code where the eclipse#generateFiles dependency resolver calls Ivy to download the sources and javadoc jars, but I can't find a way to configure Jerkar to tell Ivy to download the natives jars too and add them to the classpath.

I tried a couple things, but they didn't seem to have the effect I wanted:
```java
JkScope scopeNativesLinux = JkScope.of("natives-linux");

@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()
		.on("org.lwjgl:lwjgl:3.1.1")
		.on("org.lwjgl:lwjgl:3.1.1", scopeNativesLinux)
		.build();
}
```

Is there a way to do this if I had the right build script? Or do we need to modify Jerkar to do it?

**Comment by cuchaz** [comment]
I don't know if this helps or not, but this is what the example library I mentioned (LWJGL) thinks its Ivy config should be:
```xml
	<!-- Add to ivysettings.xml -->
	<property name="lwjgl.version" value="3.1.1"/>
	<!-- Add to build.xml -->
	<condition property="lwjgl.natives" value="natives-windows">
		<os family="Windows"/>
	</condition>
	<condition property="lwjgl.natives" value="natives-linux">
		<os name="Linux"/>
	</condition>
	<condition property="lwjgl.natives" value="natives-macos">
		<os name="Mac OS X"/>
	</condition>
	<!-- Add to ivy.xml (xmlns:m="http://ant.apache.org/ivy/maven") -->
	<dependencies>
		<dependency org="org.lwjgl" name="lwjgl" rev="${lwjgl.version}">
			<artifact name="lwjgl" type="jar"/>
			<artifact name="lwjgl" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
		<dependency org="org.lwjgl" name="lwjgl-glfw" rev="${lwjgl.version}">
			<artifact name="lwjgl-glfw" type="jar"/>
			<artifact name="lwjgl-glfw" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
		<dependency org="org.lwjgl" name="lwjgl-jemalloc" rev="${lwjgl.version}">
			<artifact name="lwjgl-jemalloc" type="jar"/>
			<artifact name="lwjgl-jemalloc" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
		<dependency org="org.lwjgl" name="lwjgl-openal" rev="${lwjgl.version}">
			<artifact name="lwjgl-openal" type="jar"/>
			<artifact name="lwjgl-openal" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
		<dependency org="org.lwjgl" name="lwjgl-opengl" rev="${lwjgl.version}">
			<artifact name="lwjgl-opengl" type="jar"/>
			<artifact name="lwjgl-opengl" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
		<dependency org="org.lwjgl" name="lwjgl-stb" rev="${lwjgl.version}">
			<artifact name="lwjgl-stb" type="jar"/>
			<artifact name="lwjgl-stb" type="jar" m:classifier="${lwjgl.natives}"/>
		</dependency>
	</dependencies>
```
according to the [LWJGL download page](https://www.lwjgl.org/download).

**Comment by cuchaz** [comment]
Ugh... this was a tough one to find a workaround for. It seems Ivy was just not designed to handle multiple artifacts per dependency. I was looking at Ivy's source a lot... `sources` and `javadoc` works kinda ok because they friggin' hard-coded it! It's really tremendously hard of get other kinds of artifacts to work though. =(

Anyway, here's my workaround. I noticed that Jerkar supports the classifier Gradle-style syntax, so that helps. But Ivy needs some coaxing to use them correctly.

Here's my build script:
```java
@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()
		.on("org.lwjgl:lwjgl:3:1:1")
		.on(uglyHack("org.lwjgl:lwjgl:3:1:1:natives-linux"))
		// ... and other libs, LWJGL has many
		.build();
}

private File uglyHack(String desc) {
	JkModuleDependency modDep = JkModuleDependency.of(desc);
	if (modDep.classifier() == null) {
		throw new IllegalArgumentException("dependency must have classifier to resolve artifact directly");
	}
	return buildRepos().get(modDep);
}
```
and this requires a [small patch to Jerkar's Ivy routines](https://github.com/cuchaz/jerkar/commit/0debc6404c50133d19ceefb1208d3898dd06240c) to make work.

It's not ideal, but it actually works for me. Maybe it's a hint for how to update Jerkar to handle "classifier" jars like `natives-*` on the classpath.

**Comment by djeang** [comment]
You can use JkModuleDependency #classifier method to set the classifier of a dependency. 
A short hand exists using syntax ´groupName:moduleName:version:classifier´. Be carefull, version should not have ':' separator but '.' to be properly parsed using this short hand.
´´´
@Override
public JkDependencies dependencies() {
	return JkDependencies.builder()
		.on("org.lwjgl:lwjgl:3.1.1:natives-linux")
		.build();
}
´´´

Another way is to simply put the binary in [your projet]/build/libs/runtime folder. Jerkar will include it in your runtime dependencies automatically. ( You can put in in [your projet]/build/libs/compile, test, provided as well).

**Comment by djeang** [comment]
Also i noticed you use `org.lwjgl:lwjgl:3:1:1:natives-linux` instead of `org.lwjgl:lwjgl:3.1.1:natives-linux`.
Is the problem persisting using the correct notation ?

**Comment by cuchaz** [comment]
Yeah, I was originally downloading the natives jars manually, but it was becoming tedious. I figured I'd try to find a way to make Jerkar do it for me. =P

And, sorry about the `:` in the version. That's a typo. I was simplifying my actual build script for the Github issue and made a copy/paste error. My actual build script is here:
```java
	@Override
	public JkDependencies dependencies() {
		
		final String LWJGLVersion = "3.1.1";
		
		// NOTE: don't forget to change the Eclipse JRE to the -noFX version!
		// TODO: find out how to make jerkar do that
		
		return JkDependencies.builder()
				
			// OpenJFX projects
			.on(graphicsProject.asJavaDependency())
			.on(fxmlProject.asJavaDependency())
			
			// 3rd-party libs
			.on(         "org.lwjgl:lwjgl:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl:" + LWJGLVersion + ":natives-linux"))
			.on(         "org.lwjgl:lwjgl-glfw:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl-glfw:" + LWJGLVersion + ":natives-linux"))
			.on(         "org.lwjgl:lwjgl-jemalloc:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl-jemalloc:" + LWJGLVersion + ":natives-linux"))
			.on(         "org.lwjgl:lwjgl-opengl:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl-opengl:" + LWJGLVersion + ":natives-linux"))
			.on(         "org.lwjgl:lwjgl-openal:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl-openal:" + LWJGLVersion + ":natives-linux"))
			.on(         "org.lwjgl:lwjgl-stb:" + LWJGLVersion)
			.on(uglyHack("org.lwjgl:lwjgl-stb:" + LWJGLVersion + ":natives-linux"))
			
			.build();
	}
```

which reminds me... I need to find a way to make Jerkar use an arbitrary JDK too. But that's a separate issue. =P

When I use the correct version strings, the problem still happens. Jerkar (via Ivy) ignores the classifier completely and downloads the regular "jar" artifacts.

**Comment by cuchaz** [comment]
Oh, and for posterity, [here's where Ivy hard codes `sources` and `javadoc` to make them work correctly.](https://github.com/apache/ant-ivy/blob/2.4.x/src/java/org/apache/ivy/plugins/parser/m2/PomModuleDescriptorParser.java#L303)

**Comment by djeang** [comment]
Ok I have reproduced the problem. I don't think it's a Ivy problem but probably a module key computed without involving classifier... I am having a look soon.

By the way, by reproducing the problem I figured out that you could refactor your build in more elegant way, thanks to Java capabilities

```
   @Override
    public JkDependencies dependencies() {
        return JkDependencies.builder()
                .on(lwjgl(""))
                .on(lwjgl("-glfw"))
                .on(lwjgl("-jemalloc"))
                .on(lwjgl("-opengl"))
                .on(lwjgl("-openal"))
                .on(lwjgl("-stb"))
                .build();
    }

    private static JkDependencies lwjgl(String suffix) {
        String version = "3.1.1";
        JkModuleDependency dep =  JkModuleDependency.of("org.lwjgl", "lwjgl" + suffix, version);
        return JkDependencies.of(COMPILE, dep, dep.classifier("linux-native"));
    }
```

**Comment by djeang** [comment]
Sorry I spoke too fast.
I hit a 404 not found when trying to fetch directly the artifact http://central.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/3.1.1/lwjgl-3.1.1-natives-linux.jar
Which repo are you using ?

**Comment by cuchaz** [comment]
Any progress on this? I tried the latest 0.5.1 snapshot, but I can't get the natives to download.

I'm ready to release a project that uses Jerkar and LWJGL, but I'm stalled until this can be fixed. My workaround only works with a modified version of Jerkar, so the downstream users of my project can't use it.

I have to wait for this issue to be fixed before I can release my project. =(

Is there anything I can do to help?

**Comment by djeang** [comment]
I'm currently busy on it :-)
Hope I can post a fix very soon.

**Comment by djeang** [comment]
I have just pushed fix to master. 
Please can you check on your side if it's ok ?
I will release it later as it requires more tests.

**Comment by cuchaz** [comment]
It doesn't appear to be working. I used the latest master branch with this test script:
```java
	@Override
	public JkDependencies dependencies() {
		return JkDependencies.builder()
			.on("org.lwjgl:lwjgl:3.1.1")
			.on("org.lwjgl:lwjgl:3.1.1:natives-linux")
			.build();
	}
```
and got this result:
```
Method generateFiles on plugin JkBuildPluginEclipse
---------------------------------------------------
|  Setting dependency resolver  ... 
|   \ Done in 0.208 seconds.
|  No dependency declared with scope 'provided'
|  No dependency declared with scope 'runtime'
|  No dependency declared with scope 'test'
|  Resolving dependencies for scope 'compile' ... 
|  |  1 artifacts.
|   \ Done in 0.218 seconds.
 \ Done in 0.46 seconds.
```
There should be 2 artifacts, instead of just 1.

**Comment by cuchaz** [comment]
In the meantime, I may just write a script that manually downloads the native jars to the `build/libs/runtime` folder so I can continue with my project release. That way you don't have to feel rushed to fix this. =)

**Comment by djeang** [comment]
Logs mention1 artifact becauses it consideres "all artifacts being of the same module" a single artifact, but both are present in reallity so you can use jerkar as is : I have to fix the log mention.

To be sure, you can execute those line within your build 
```
JkPath depPath = this.depsFor(COMPILE);
System.out.println(depPath.withoutDoubloons());
```

You'll see that the two artefacts are part of your COMPILE path.

**Comment by cuchaz** [comment]
Ok, the `JkPath` shows the correct jars, so they're downloading correctly, yay! That's an improvement. =)

But they still do not appear in Eclipse's `.classpath` after `eclipse#generateFiles` is called:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="build/def" output="build/output/def-bin"/>
	<classpathentry kind="src" including="**/*" path="src"/>
	<classpathentry kind="src" including="**/*" path="resources"/>
	<classpathentry kind="var" path="JERKAR_REPO/org.lwjgl/lwjgl/jars/lwjgl-3.1.1.jar" sourcepath="JERKAR_REPO/org.lwjgl/lwjgl/sources/lwjgl-3.1.1-sources.jar">
		<attributes>
			<attribute name="javadoc_location" value="jar:file://home/jeff/.jerkar/cache/repo/org.lwjgl/lwjgl/javadocs/lwjgl-3.1.1-javadoc.jar"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="var" path="JERKAR_HOME/org.jerkar.core-all.jar" sourcepath="JERKAR_HOME/libs-sources/org.jerkar.core-all-sources.jar"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by cuchaz** [comment]
It works! Hooray! Thanks bunch for your help! =)

When it's released, I can update my build scripts on released projects.

**Comment by djeang** [comment]
I will. In meantime you can use Jerkar embedded mode. In this mode Jerkar jar is embbeded within your project (commited on your CVS) so anyone can build regardless Jerkar version installed on build machine.
